<?php
$offers = $block->getItems();
?>
<div class="card-slider no-display">
    <?php foreach ($offers as $offer): ?>
        <div class="offer-slide">
            <div class="img">
                <img src="<?= $block->escapeUrl($this->getImageUrl($offer->getImagePath())) ?>" alt="<?= $block->escapeHtml($offer->getName()) ?>">
            </div>
            <div class="offer-content">
                    <p class="offer-name"><?= $block->escapeHtml($offer->getName()) ?></p>
                    <p class="offer-description"><?= $block->escapeHtml($offer->getDescription()) ?></p>
            </div>
            <div class="btn-content">
                    <a href="<?= $block->escapeUrl($offer->getOfferUrl()) ?>" class="action primary">En savoir plus</a>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    require(['jquery', 'dnd/slick'], function ($) {
        $(document).ready(function () {
            $('.card-slider').slick({
                // dots: true,
                infinite: true,
                slidesToShow: 1, // Afficher un élément à la fois
                slidesToScroll: 1 // Faire défiler un élément à la fois
            });
        });
    });
</script>

<style>

</style>


